# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: servePut.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eservePut.proto\"9\n\x0ePutFileRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x15\n\rfile_as_bytes\x18\x02 \x01(\x0c\"!\n\x0fPutFileResponse\x12\x0e\n\x06status\x18\x01 \x01(\t28\n\x08ServePut\x12,\n\x07PutFile\x12\x0f.PutFileRequest\x1a\x10.PutFileResponseb\x06proto3')



_PUTFILEREQUEST = DESCRIPTOR.message_types_by_name['PutFileRequest']
_PUTFILERESPONSE = DESCRIPTOR.message_types_by_name['PutFileResponse']
PutFileRequest = _reflection.GeneratedProtocolMessageType('PutFileRequest', (_message.Message,), {
  'DESCRIPTOR' : _PUTFILEREQUEST,
  '__module__' : 'servePut_pb2'
  # @@protoc_insertion_point(class_scope:PutFileRequest)
  })
_sym_db.RegisterMessage(PutFileRequest)

PutFileResponse = _reflection.GeneratedProtocolMessageType('PutFileResponse', (_message.Message,), {
  'DESCRIPTOR' : _PUTFILERESPONSE,
  '__module__' : 'servePut_pb2'
  # @@protoc_insertion_point(class_scope:PutFileResponse)
  })
_sym_db.RegisterMessage(PutFileResponse)

_SERVEPUT = DESCRIPTOR.services_by_name['ServePut']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PUTFILEREQUEST._serialized_start=18
  _PUTFILEREQUEST._serialized_end=75
  _PUTFILERESPONSE._serialized_start=77
  _PUTFILERESPONSE._serialized_end=110
  _SERVEPUT._serialized_start=112
  _SERVEPUT._serialized_end=168
# @@protoc_insertion_point(module_scope)
